version: "3.2"
services: 
  go-api:
    image: ghcr.io/omenejoseph/go-api:1.0.0
    ports: 
      - "8081:8080"
    networks:
      - backend
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.go-api.rule=Host(`go-api.omenejoseph.co.uk`)"
      - "traefik.http.routers.go-api.entrypoints=web"  

  node-api:
    image: ghcr.io/omenejoseph/node-api:1.0.0
    ports: 
      - "3000:3000"
    networks:
      - backend  
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.node-api.rule=Host(`node-api.omenejoseph.co.uk`)"
      - "traefik.http.routers.node-api.entrypoints=web"    

  db:
    image: "mysql:8.1.0" 
    volumes:
       - db-data:/var/lib/mysql/data
    environment:
      - MYSQL_ROOT_PASSWORD=root  
    networks:
      - backend

  traefik:
    image: traefik:v2.5
    ports:
      - "80:80"
      - "8080:8080" # The Web UI (optional)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --api.insecure=true # Enables the web UI
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    networks:
      - web  
    
volumes:
  db-data:
networks:
  backend:
  web:

