name: Deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version 1.0.0'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      env:
        CR_PAT: ${{ secrets.CR_PAT }}
        USERNAME: ${{ vars.USERNAME }}
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_IP: ${{ vars.SERVER_IP }}
      run: |
        echo "$PRIVATE_KEY" > private_key
        chmod 400 private_key
        mkdir -p ~/.ssh
        touch ~/.ssh/known_hosts
        ssh-keyscan -H ${SERVER_IP} >> ~/.ssh/known_hosts
        cat ~/.ssh/known_hosts

    - name: Pull and Run containers
      env:
        VERSION: ${{ github.event.inputs.version }}
        SERVER_IP: ${{ vars.SERVER_IP }}
      run: |
        ssh -T -i private_key root@$SERVER_IP  << EOF
        echo Setting up Docker login...
        echo $CR_PAT
        echo $USERNAME
        echo I am here...
        echo $CR_PAT | docker login ghcr.io -u $USERNAME --password-stdin
        docker pull gcr.io/omenejoseph/go-api:$VERSION
        docker pull gcr.io/omenejoseph/node-api:$VERSION
        docker run -d -p 0.0.0.0:8080:8080 --name go-api gcr.io/omenejoseph/go-api:$VERSION
        docker run -d -p 0.0.0.0:3000:3000 --name node-api gcr.io/omenejoseph/node-api:$VERSION
        EOF
