name: Deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version 1.0.0'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      env:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_IP: ${{ vars.SERVER_IP }}
      run: |
        echo "$PRIVATE_KEY" > private_key
        chmod 400 private_key
        mkdir -p ~/.ssh
        touch ~/.ssh/known_hosts
        ssh-keyscan -H ${SERVER_IP} >> ~/.ssh/known_hosts

    - name: Copy script to server
      env:
        SERVER_IP: ${{ vars.SERVER_IP }}
      run: |
        scp -i private_key create-docker-compose.sh root@$SERVER_IP:/tmp/    

    - name: Execute script and run containers
      env:
        VERSION: ${{ github.event.inputs.version }}
        SERVER_IP: ${{ vars.SERVER_IP }}
        CR_PAT: ${{ secrets.CR_PAT }}
        USERNAME: ${{ vars.USERNAME }}
      run: |
        ssh -T -i private_key root@$SERVER_IP  << EOF
        echo Setting up Docker login.....
        echo $CR_PAT | docker login ghcr.io -u $USERNAME --password-stdin
        bash /tmp/create-docker-compose.sh $VERSION 
        docker compose -f docker-compose-prod.yml up -d
        EOF
